### PR TITLE
Modernise merge

### PR DESCRIPTION
**Pull request by lokedhs**
The modernise branch as a single commit

### CODE REVIEW

**Comment by dabridgham** [comment]
Has TERMCAP gone by the wayside then?  I always liked it better than terminfo.

**Comment by lokedhs** [comment]
Yes. I cleaned it out for a few reasons: First and foremost it made the entire codebase quite messy, and further improvements are harder to do because of it, since terminfo has more features than termcap. Secondly, termcap has been legacy for quite some time, and modern Linux distributions don't even ship with termcap anymore. Thirdly, keeping two systems in sync is hard, and there was a problem with terminfo that made it not even compile. Having two versions makes testing much harder.

What was it about ther termcap version that you liked better? I didn't really see anything that termcap did that terminfo didn't do better. But if I am mistaken, perhaps I can fix terminfo so that you don't have this concern anymore?

There is the small issue that terminfo can be found in libncurses.so on Linux, but other OS'es has a different library that provides the same functionality. I don't think anyone wants to use autoconf, so some better documentation on this is probably needed.

**Comment by dabridgham** [comment]
Terminfo always came across to me as extra complexity for no benefit
that I cared about.  As a general rule I prefer the text files over
binary config files and the ability to cons up a TERMCAP string on the
fly as an environment variable matched what the SUPDUP server needed
quite nicely (once the problem of passing that environment variable
through /bin/login was solved).  However, if TERMCAP is deprecated (sure
enough, it's not on the Linux machine I'm typing this on and I never
noticed) then it's the right thing to remove it from the SUPDUP code.

**Comment by larsbrinkhoff** [comment]
I'm merging this, but I have split it into a few commits.

**Comment by larsbrinkhoff** [comment]
I tested this by logging into an ITS, running a program which prints all extended characters in super-image mode, and checking that EMACS runs ok.

**Pull request merged**
