### PR TITLE
Linux supdupd

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
These are @sgtatham's patches to make supdupd work on Linux.  I'm submitting them as a draft for consideration.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
CC @dabridgham who might have been involved with the original version.

**Comment by larsbrinkhoff** [comment]
Simon notes:
>  Also, now I think about it, a really good _test_ SUPDUP server wouldn't want to talk to a shell at all. It would present a completely faked login environment, whose main feature would be the ability to exercise all the terminal control codes and output every meaningful character value.

That is certainly an interesting idea.  The only automated "test" now is to check that the supdup client compiles.

**Comment by larsbrinkhoff** [comment]
According to https://www.gnu.org/software/gnulib/manual/html_node/vhangup.html, the vhangup system call does not exist on most platforms.

**Comment by dabridgham** [comment]
I am indeed the person who's to blame for the original version of this supdup server for Unix.  Looking back over the files, it's amazing how little I remember of the code I wrote 35 years ago.  What I see in my mind's eye are the features I've thought about adding.  Anyway, I couldn't be more pleased that someone is picking it up and making it work on today's Linux.

That -Wall flagged that bug with 1+a|b is remarkable.  Good catch.

**Comment by larsbrinkhoff** [comment]
I added some fixes on top of @sgtatham's.  The server is not built or installed by default, since using it will require some expert knowledge.

**Pull request merged**
